import React,{useState} from 'react';
const DETAILS=[
{id:'F01',title:'Strip foundation and cavity wall',parts:['Concrete strip footing — width/depth to structural engineer and ground assessment','Loadbearing masonry centred on foundation; below-ground blocks to specification','DPC minimum 150 mm above finished external ground level','Continuous cavity insulation and proprietary insulated cavity closer','DPM lapped and sealed to DPC; radon/gas measures subject to site assessment'],checks:['Ground bearing capacity and tree influence','Foundation width/depth by engineer and Building Control','Drain proximity and services','Cavity dimensions, insulation and wall ties']},
{id:'W01',title:'Insulated cavity wall and opening',parts:['External facing masonry / ventilated drained cavity where specified','Insulation thickness and conductivity from approved U-value calculation','Internal loadbearing leaf and internal finish as designed','Insulated cavity closer, cavity tray, stop ends and weep vents at openings','Lintel to structural schedule; cavity barriers and fire stopping as applicable'],checks:['Wall U-value calculation and condensation assessment','Lintel load and bearing','Exposure zone and cavity specification','Opening head/sill/jamb thermal bridging']},
{id:'G01',title:'Ground-bearing insulated floor',parts:['Compacted suitable sub-base and blinding as designed','DPM / gas membrane with sealed laps and junction to wall DPC','Concrete slab thickness and reinforcement subject to engineer','Floor insulation to verified Part L specification; perimeter upstand','Screed / finish with movement joints as specified'],checks:['Ground gas and moisture conditions','Insulation U-value and compressive strength','Slab design and floor levels','Thermal bridge at wall perimeter']},
{id:'R01',title:'Pitched roof eaves and ridge',parts:['Roof tiles rated for actual pitch and exposure; fixings to manufacturer design','Battens and underlay to current applicable standards','Rafters/trusses and restraint straps to structural design','Insulation continuity at eaves with ventilation provision as designed','Ceiling vapour control and airtightness layer; sealed penetrations'],checks:['Actual roof pitch and tile minimum pitch','Roof U-value and condensation risk','Ventilation strategy: cold or warm roof','Fire stopping, party-wall junction and structural restraint']},
{id:'D01',title:'Below-ground drainage junction',parts:['Foul and surface drainage kept separate unless approved otherwise','Pipe sizes, falls and bedding to approved drainage design','Access chambers at changes of direction and suitable maintenance points','Sealed connection to existing system subject to survey and approval','Sleeves, lintels and flexible joints at building penetrations'],checks:['Invert levels and outfall capacity','Drainage authority approval and build-over consent','Pipe gradients and cover','Testing and inspection before backfill']}
];

// Detail register: each variation is a separately selectable drawing-sheet entry.
// All dimensions and performance values remain design-dependent until reviewed.
const GROUPS=[
['A','Foundations',['Trench-fill foundation','Raft foundation','Piled foundation and ground beam','Stepped foundation','Foundation near existing drains','Foundation adjacent to existing building','Foundation near trees','Foundation at change in ground level','Foundation with retaining wall']],
['B','Ground floors',['Suspended timber floor','Beam-and-block floor','Suspended concrete slab','Insulated solid floor','Existing floor thermal upgrade','Floor DPM to wall DPC junction','Floor gas membrane junction','Level-access threshold','Garage floor junction']],
['C','External walls',['Brick and block cavity wall','Full-fill insulated cavity wall','Partial-fill insulated cavity wall','Timber-frame external wall','Solid masonry wall insulation','External wall insulation','Internal wall insulation','Cavity tray over opening','Cavity tray at abutment','Movement joint','Wall tie arrangement','Cavity barrier at floor','Cavity barrier at roof','Wall base and DPC','Parapet wall']],
['D','Internal walls',['Loadbearing block partition','Timber stud partition','Metal stud partition','Acoustic partition','Fire-resisting partition','Wall to floor junction','Wall to roof junction','Service penetration through wall']],
['E','Upper floors',['Solid timber joist floor','Engineered I-joist floor','Metal-web joist floor','Steel beam supporting floor','Joist hanger bearing','Stairwell opening trimming','Floor acoustic separation','Floor fire protection','Floor to external wall junction']],
['F','Roofs',['Cold pitched roof eaves','Warm pitched roof','Vaulted roof insulation','Low-pitch tiled roof','Pitched roof ridge','Pitched roof verge','Pitched roof valley','Pitched roof abutment','Pitched roof chimney flashing','Rooflight head and sill','Warm flat roof','Cold flat roof','Inverted flat roof','Flat roof parapet','Flat roof outlet','Roof terrace','Dormer cheek','Dormer roof junction','Party-wall roof junction','Solar panel roof penetration']],
['G','Doors and windows',['Window head','Window jamb','Window sill','Door head','Door jamb','External door threshold','Cavity closer','Fire door frame','Roof window','Escape window','Glazed safety barrier']],
['H','Stairs and guarding',['Straight flight stairs','Winder stairs','Quarter landing','Half landing','Stair headroom','Stair guarding','Balustrade fixing','Handrail return','External access steps']],
['J','Drainage',['Foul drainage trench','Surface water drainage trench','Inspection chamber','Manhole','Drain through foundation','Drain beneath building','Rainwater downpipe','Soakaway','Attenuation crate','Channel drain','Below-ground connection','Above-ground soil stack','Air admittance valve','Drainage ventilation terminal']],
['K','Fire safety',['Cavity barrier at opening','Cavity barrier at compartment line','Fire stopping around pipe','Fire stopping around cable','Fire stopping at floor edge','Fire-rated wall junction','Compartment floor','Protected stair enclosure','Fire door installation','Smoke alarm location','Roof-space compartment barrier']],
['L','Thermal and airtightness',['Wall to foundation thermal bridge','Wall to floor thermal bridge','Wall to roof thermal bridge','Window reveal insulation','Door threshold insulation','Balcony thermal break','Airtightness at service penetration','Vapour control layer junction','Insulation continuity at eaves']],
['M','Ventilation',['Kitchen extract duct','Bathroom extract duct','Background ventilator','Continuous mechanical extract','MVHR supply and extract','Roof duct terminal','Wall duct terminal','Subfloor ventilation','Roof void ventilation','Ventilation fire damper']],
['N','Plumbing and heating',['Hot and cold water distribution','Unvented hot water cylinder','Boiler flue penetration','Air source heat pump connection','Underfloor heating build-up','Radiator pipe penetration','Condensate discharge','Sanitary appliance drainage','Water service entry']],
['P','Electrical',['Consumer unit location','Electrical cable in wall','Electrical cable through fire barrier','Recessed downlight fire protection','External electrical supply','EV charger connection','Smoke and heat alarm wiring','Electrical service entry']],
['Q','External works',['Level-access path','External ramp','Retaining wall','Patio to DPC junction','Paving and surface drainage','Boundary wall','Garden steps','External drainage channel']],
['R','Existing buildings',['New extension to existing wall','New roof to existing roof','Existing wall opening and beam','Chimney removal and support','Loft conversion floor','Loft conversion dormer','Existing damp wall remediation','Existing roof insulation upgrade','Party wall junction','Existing foundations underpinning']]
];
const REGISTER=GROUPS.flatMap(([group,category,names])=>names.map((name,i)=>({id:group+String(i+1).padStart(2,'0'),category,title:name,group})));
const genericSpecification=['Confirm the relevant existing and proposed drawing geometry, levels and dimensions before selecting this detail.','Specify products and construction build-up only after checking the applicable Approved Documents, manufacturer instructions and exposure conditions.','Provide continuous moisture, thermal, air and fire-control layers where applicable; coordinate interfaces with adjoining elements.','Obtain structural calculations and connection design where loads, spans, bearings or ground conditions are involved.'];
const genericChecks=['Design responsibility and site-specific applicability','Measured dimensions and levels','Part L performance / condensation where relevant','Fire, acoustic, moisture and accessibility requirements where relevant','Building Control inspection and specialist sign-off'];
const dim=(x1,y1,x2,y2,label)=> <g stroke="#9b2431" strokeWidth="1" fill="#9b2431"><line x1={x1} y1={y1} x2={x2} y2={y2}/><text x={(x1+x2)/2+5} y={(y1+y2)/2-5} fontSize="10" stroke="none">{label}</text></g>;
function Drawing({id}){const common={stroke:'#17365d',strokeWidth:2,fill:'none'};return <svg viewBox="0 0 650 300" role="img" aria-label={'Indicative construction section '+id} style={{width:'100%',background:'#fff',border:'1px solid #ccd6e1'}}>
<g {...common}>{id==='F01'?<><rect x="210" y="65" width="55" height="150"/><rect x="320" y="65" width="55" height="150"/><rect x="175" y="215" width="235" height="55" fill="#e7edf4"/><path d="M265 65 V215 M320 65 V215" strokeDasharray="6 4"/><path d="M180 92 H410" stroke="#9b2431" strokeWidth="4"/><path d="M180 125 H210 M375 125 H410" strokeDasharray="4 4"/></>:id==='W01'?<><rect x="195" y="40" width="55" height="210"/><rect x="320" y="40" width="55" height="210"/><rect x="250" y="40" width="70" height="210" fill="#e8f0f5"/><rect x="180" y="120" width="215" height="20" fill="#cad6e4"/><path d="M250 85 H320 M250 185 H320" strokeDasharray="5 5"/><path d="M180 145 H395" stroke="#9b2431" strokeWidth="3"/></>:id==='G01'?<><rect x="125" y="145" width="410" height="42" fill="#d4dce5"/><rect x="125" y="187" width="410" height="32" fill="#dce9f1"/><rect x="125" y="219" width="410" height="42" fill="#e9e9e9"/><path d="M125 186 H535" stroke="#9b2431" strokeWidth="3"/><rect x="130" y="80" width="45" height="65"/><rect x="485" y="80" width="45" height="65"/></>:id==='R01'?<><path d="M120 200 L325 45 L530 200"/><path d="M120 215 L325 60 L530 215" stroke="#9b2431" strokeWidth="3"/><path d="M155 200 H495"/><path d="M160 188 H490" strokeDasharray="5 4"/><path d="M200 175 V235 M450 175 V235"/><path d="M200 235 H450"/></>:<><rect x="95" y="105" width="460" height="100" fill="#e8edf2"/><path d="M95 165 H555" stroke="#9b2431" strokeWidth="4"/><path d="M165 165 V235 H260 V165 M400 165 V235 H490 V165"/><circle cx="260" cy="165" r="9"/><circle cx="400" cy="165" r="9"/></>}</g>
{dim(80,55,80,255,'VERIFY ON DESIGN') }<text x="115" y="285" fill="#9b2431" fontSize="12" fontWeight="bold">SCHEMATIC ONLY • NOT TO SCALE • NOT FOR CONSTRUCTION</text></svg>}
export default function ConstructionDetails({project}) {
const [notes,setNotes]=useState({}),[search,setSearch]=useState(''),[group,setGroup]=useState('ALL'),[selected,setSelected]=useState([]),[showRegister,setShowRegister]=useState(true);
const all=[...DETAILS.map(x=>({...x,category:'Core sections',group:'0'})),...REGISTER];
const shown=all.filter(x=>(group==='ALL'||x.group===group)&&(!search||[x.id,x.title,x.category].join(' ').toLowerCase().includes(search.toLowerCase())));
const chosen=all.filter(x=>selected.includes(x.id));
function toggle(id){setSelected(prev=>prev.includes(id)?prev.filter(x=>x!==id):[...prev,id])}
return <section className="panel constructionDetails">
<style>{`@media print {.constructionDetails .controls,.constructionDetails button,.constructionDetails input,.constructionDetails select,.constructionDetails textarea{display:none!important}.constructionDetails article{break-inside:avoid;page-break-after:always}.constructionDetails{font-family:Arial,sans-serif}.constructionDetails h2{color:#17365d}.constructionDetails article{border:0!important}}`}</style>
<h2>Architectural Construction Detail Library</h2>
<p><b>{all.length} registered construction detail types</b> across foundations, floors, walls, roofs, fire, drainage, services and alterations. Five core types include indicative schematic sections. Other entries are indexed specification/review sheets awaiting individually engineered illustrations.</p>
<p><b>Important:</b> Register entries are not dimensioned construction drawings. Every sheet is preliminary and requires project-specific architect / engineer design, applicable regulatory checks and Building Control review.</p>
<div className="controls" style={{display:'flex',gap:12,flexWrap:'wrap',margin:'15px 0'}}>
<input aria-label="Search details" placeholder="Search detail number or construction element" value={search} onChange={e=>setSearch(e.target.value)}/>
<select aria-label="Detail category" value={group} onChange={e=>setGroup(e.target.value)}><option value="ALL">All categories</option><option value="0">Core illustrated sections</option>{GROUPS.map(g=><option key={g[0]} value={g[0]}>{g[0]} — {g[1]}</option>)}</select>
<button type="button" onClick={()=>setShowRegister(v=>!v)}>{showRegister?'Hide':'Show'} detail register</button>
<button type="button" onClick={()=>window.print()}>Print / Save PDF</button>
</div>
{showRegister&&<div className="controls" style={{maxHeight:350,overflowY:'auto',border:'1px solid #ccd6e1',padding:12}}>{shown.map(d=><label key={d.id} style={{display:'block',marginBottom:8}}><input type="checkbox" checked={selected.includes(d.id)} onChange={()=>toggle(d.id)}/> <b>{d.id}</b> — {d.title} <small>({d.category})</small></label>)}</div>}
<h3>Selected drawing sheets ({chosen.length})</h3>
{!chosen.length&&<p>Select the details relevant to this project from the register above. No assumptions are made about which construction systems the project uses.</p>}
{chosen.map(d=><article key={d.id} style={{pageBreakInside:'avoid',margin:'28px 0',padding:18,border:'1px solid #ccd6e1'}}>
<h3>{d.id} — {d.title}</h3>
<p><b>UK Principal Designers Ltd</b> · Project: {project?.name||'Project not named'} · Revision P01 · Design review only</p>
{d.group==='0'?<Drawing id={d.id}/>:<div style={{minHeight:135,border:'2px dashed #8b9bad',padding:24,textAlign:'center'}}><b>PROJECT-SPECIFIC DETAIL DRAWING REQUIRED</b><p>Sheet registered; dimensioned section not yet authored. Do not issue as a construction drawing.</p></div>}
<h4>Construction specification / design prompts</h4><ol>{(d.parts||genericSpecification).map(x=><li key={x}>{x}</li>)}</ol>
<h4>Design confirmations before issue</h4><ul>{(d.checks||genericChecks).map(x=><li key={x}>{x}</li>)}</ul>
<label className="controls">Review notes<textarea rows="3" value={notes[d.id]||''} onChange={e=>setNotes(v=>({...v,[d.id]:e.target.value}))} placeholder="Local review notes (not saved to the project database)"/></label>
<p><small>NOT FOR CONSTRUCTION. Dimensions, U-values, materials, structural requirements and regulatory compliance must be verified by competent designers.</small></p>
</article>)}
</section>}
