import React,{useState} from 'react';
const DETAILS=[
{id:'F01',title:'Strip foundation and cavity wall',parts:['Concrete strip footing — width/depth to structural engineer and ground assessment','Loadbearing masonry centred on foundation; below-ground blocks to specification','DPC minimum 150 mm above finished external ground level','Continuous cavity insulation and proprietary insulated cavity closer','DPM lapped and sealed to DPC; radon/gas measures subject to site assessment'],checks:['Ground bearing capacity and tree influence','Foundation width/depth by engineer and Building Control','Drain proximity and services','Cavity dimensions, insulation and wall ties']},
{id:'W01',title:'Insulated cavity wall and opening',parts:['External facing masonry / ventilated drained cavity where specified','Insulation thickness and conductivity from approved U-value calculation','Internal loadbearing leaf and internal finish as designed','Insulated cavity closer, cavity tray, stop ends and weep vents at openings','Lintel to structural schedule; cavity barriers and fire stopping as applicable'],checks:['Wall U-value calculation and condensation assessment','Lintel load and bearing','Exposure zone and cavity specification','Opening head/sill/jamb thermal bridging']},
{id:'G01',title:'Ground-bearing insulated floor',parts:['Compacted suitable sub-base and blinding as designed','DPM / gas membrane with sealed laps and junction to wall DPC','Concrete slab thickness and reinforcement subject to engineer','Floor insulation to verified Part L specification; perimeter upstand','Screed / finish with movement joints as specified'],checks:['Ground gas and moisture conditions','Insulation U-value and compressive strength','Slab design and floor levels','Thermal bridge at wall perimeter']},
{id:'R01',title:'Pitched roof eaves and ridge',parts:['Roof tiles rated for actual pitch and exposure; fixings to manufacturer design','Battens and underlay to current applicable standards','Rafters/trusses and restraint straps to structural design','Insulation continuity at eaves with ventilation provision as designed','Ceiling vapour control and airtightness layer; sealed penetrations'],checks:['Actual roof pitch and tile minimum pitch','Roof U-value and condensation risk','Ventilation strategy: cold or warm roof','Fire stopping, party-wall junction and structural restraint']},
{id:'D01',title:'Below-ground drainage junction',parts:['Foul and surface drainage kept separate unless approved otherwise','Pipe sizes, falls and bedding to approved drainage design','Access chambers at changes of direction and suitable maintenance points','Sealed connection to existing system subject to survey and approval','Sleeves, lintels and flexible joints at building penetrations'],checks:['Invert levels and outfall capacity','Drainage authority approval and build-over consent','Pipe gradients and cover','Testing and inspection before backfill']}
];
const dim=(x1,y1,x2,y2,label)=> <g stroke="#9b2431" strokeWidth="1" fill="#9b2431"><line x1={x1} y1={y1} x2={x2} y2={y2}/><text x={(x1+x2)/2+5} y={(y1+y2)/2-5} fontSize="10" stroke="none">{label}</text></g>;
function Drawing({id}){const common={stroke:'#17365d',strokeWidth:2,fill:'none'};return <svg viewBox="0 0 650 300" role="img" aria-label={'Indicative construction section '+id} style={{width:'100%',background:'#fff',border:'1px solid #ccd6e1'}}>
<g {...common}>{id==='F01'?<><rect x="210" y="65" width="55" height="150"/><rect x="320" y="65" width="55" height="150"/><rect x="175" y="215" width="235" height="55" fill="#e7edf4"/><path d="M265 65 V215 M320 65 V215" strokeDasharray="6 4"/><path d="M180 92 H410" stroke="#9b2431" strokeWidth="4"/><path d="M180 125 H210 M375 125 H410" strokeDasharray="4 4"/></>:id==='W01'?<><rect x="195" y="40" width="55" height="210"/><rect x="320" y="40" width="55" height="210"/><rect x="250" y="40" width="70" height="210" fill="#e8f0f5"/><rect x="180" y="120" width="215" height="20" fill="#cad6e4"/><path d="M250 85 H320 M250 185 H320" strokeDasharray="5 5"/><path d="M180 145 H395" stroke="#9b2431" strokeWidth="3"/></>:id==='G01'?<><rect x="125" y="145" width="410" height="42" fill="#d4dce5"/><rect x="125" y="187" width="410" height="32" fill="#dce9f1"/><rect x="125" y="219" width="410" height="42" fill="#e9e9e9"/><path d="M125 186 H535" stroke="#9b2431" strokeWidth="3"/><rect x="130" y="80" width="45" height="65"/><rect x="485" y="80" width="45" height="65"/></>:id==='R01'?<><path d="M120 200 L325 45 L530 200"/><path d="M120 215 L325 60 L530 215" stroke="#9b2431" strokeWidth="3"/><path d="M155 200 H495"/><path d="M160 188 H490" strokeDasharray="5 4"/><path d="M200 175 V235 M450 175 V235"/><path d="M200 235 H450"/></>:<><rect x="95" y="105" width="460" height="100" fill="#e8edf2"/><path d="M95 165 H555" stroke="#9b2431" strokeWidth="4"/><path d="M165 165 V235 H260 V165 M400 165 V235 H490 V165"/><circle cx="260" cy="165" r="9"/><circle cx="400" cy="165" r="9"/></>}</g>
{dim(80,55,80,255,'VERIFY ON DESIGN') }<text x="115" y="285" fill="#9b2431" fontSize="12" fontWeight="bold">SCHEMATIC ONLY • NOT TO SCALE • NOT FOR CONSTRUCTION</text></svg>}
export default function ConstructionDetails({project}){const[notes,setNotes]=useState({});function print(){window.print()}return <section className="panel constructionDetails"><h2>Architectural Construction Detail Sheets</h2><p>Indicative technical section diagrams and specification prompts. Confirm dimensions, U-values, structural design, site conditions and applicable Approved Documents before construction issue.</p><button type="button" onClick={print}>Print detail sheets / Save as PDF</button>{DETAILS.map(d=><article key={d.id} style={{pageBreakInside:'avoid',margin:'28px 0',padding:18,border:'1px solid #ccd6e1'}}><h3>{d.id} — {d.title}</h3><p><b>Project:</b> {project.name} · {project.site_address||'Site address not confirmed'} · Revision P01 — For design review</p><Drawing id={d.id}/><h4>Construction specification — to be verified</h4><ol>{d.parts.map(x=><li key={x}>{x}</li>)}</ol><h4>Mandatory design confirmations</h4><ul>{d.checks.map(x=><li key={x}>{x}</li>)}</ul><label>Designer / engineer review notes<textarea rows="3" value={notes[d.id]||''} onChange={e=>setNotes({...notes,[d.id]:e.target.value})} placeholder="Record review comments; local draft only until saved to project records."/></label><p><small>Not a substitute for dimensioned architect/engineer drawings, proprietary installation instructions or Building Control acceptance.</small></p></article>)}</section>}
