import React,{useEffect,useRef,useState} from 'react';
import {Document,Packer,Paragraph,TextRun,Table,TableRow,TableCell,HeadingLevel,ImageRun} from 'docx';
import * as pdfjs from 'pdfjs-dist';
import * as XLSX from 'xlsx';
import './estimates.css';
pdfjs.GlobalWorkerOptions.workerSrc=new URL('pdfjs-dist/build/pdf.worker.min.mjs',import.meta.url).toString();
const fresh={items:[],highlights:[],builder_id:'',overheads:15,profit:10,vat:20};
const initialItem={description:'',trade:'General',drawing:'',quantity:0,unit:'m²',material_rate:0,plant_rate:0,labour_hours:0,labour_rate:0,supplier:'',price_url:'',status:'Needs verification'};
const money=n=>'£'+(Number(n)||0).toLocaleString('en-GB',{minimumFractionDigits:2,maximumFractionDigits:2});
const num=v=>Number(v)||0;
const perLine=i=>num(i.quantity)*(num(i.material_rate)+num(i.plant_rate)+num(i.labour_hours)*num(i.labour_rate));
export default function Estimates({db,project,docs=[]}){
 const [estimate,setEstimate]=useState({...fresh,...project.estimate_data});
 const [builders,setBuilders]=useState([]),[builderForm,setBuilderForm]=useState(null);
 const [item,setItem]=useState(initialItem),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
 const [drawing,setDrawing]=useState(''),[page,setPage]=useState(1),[pageCount,setPageCount]=useState(1),[image,setImage]=useState(''),[dimensions,setDimensions]=useState([0,0]);
 const [calibrate,setCalibrate]=useState(false),[reference,setReference]=useState(''),[calibrationMetres,setCalibrationMetres]=useState(''),[drag,setDrag]=useState(null),[hover,setHover]=useState(null),[markName,setMarkName]=useState('New work'),[stage,setStage]=useState('Proposed');
 const canvas=useRef(null),overlay=useRef(null);
 const fileDocs=docs.filter(d=>/\.(pdf|png|jpg|jpeg)$/i.test(d.document_no||d.title||d.file_path||''));
 useEffect(()=>{db.from('estimate_builders').select('*').order('name').then(({data,error})=>{if(!error)setBuilders(data||[])});},[db]);
 useEffect(()=>{let cancelled=false;async function load(){
   setImage('');if(!drawing)return;
   const d=fileDocs.find(x=>x.id===drawing);if(!d)return;
   const {data,error}=await db.storage.from('project-files').createSignedUrl(d.file_path,1200);
   if(error||!data?.signedUrl){setNotice(error?.message||'Drawing could not be opened');return}
   try{const url=data.signedUrl,ext=(d.document_no||d.title||d.file_path||'').split('.').pop().toLowerCase();
     if(ext!=='pdf'){if(!cancelled){setImage(url);setPageCount(1)}return}
     const doc=await pdfjs.getDocument({url}).promise;if(cancelled)return;
     setPageCount(doc.numPages);const pg=await doc.getPage(Math.min(page,doc.numPages));if(cancelled)return;
     const viewport=pg.getViewport({scale:1.4});const c=canvas.current;if(!c)return;c.width=viewport.width;c.height=viewport.height;
     await pg.render({canvasContext:c.getContext('2d'),viewport}).promise;
     if(!cancelled)setDimensions([viewport.width,viewport.height])
   }catch(e){if(!cancelled)setNotice('Drawing preview failed: '+e.message)}
 }load();return()=>{cancelled=true}},[drawing,page,docs,db]);
 function patch(k,v){setEstimate(x=>({...x,[k]:v}))}
 async function save(next=estimate){setBusy(true);try{const{error}=await db.from('projects').update({estimate_data:next}).eq('id',project.id);setNotice(error?'Save failed: '+error.message:'Estimate and drawing highlights saved')}finally{setBusy(false)}}
 async function uploadBuilderLogo(f){if(!f)return;const path='builder-logos/'+Date.now()+'-'+f.name.replace(/[^A-Za-z0-9._-]/g,'_');const {error}=await db.storage.from('project-files').upload(path,f);if(error)return alert(error.message);setBuilderForm(b=>({...b,logo_path:path}));setNotice('Logo uploaded securely. Save the builder to keep it.');}
 async function createBuilder(){if(!builderForm?.name?.trim())return alert('Enter builder company name');const{data,error}=await db.from('estimate_builders').insert(builderForm).select().single();if(error)return alert(error.message);setBuilders(x=>[...x,data]);patch('builder_id',data.id);setBuilderForm(null)}
 const builder=builders.find(b=>b.id===estimate.builder_id);
 function point(e){const rect=overlay.current.getBoundingClientRect();return {x:Math.max(0,Math.min(1,(e.clientX-rect.left)/rect.width)),y:Math.max(0,Math.min(1,(e.clientY-rect.top)/rect.height))}}
 function start(e){if(!drawing)return;e.preventDefault();overlay.current.setPointerCapture(e.pointerId);const p=point(e);setDrag(p);setHover(p)}
 function finish(e){if(!drag)return;const end=point(e),x=Math.min(end.x,drag.x),y=Math.min(end.y,drag.y),w=Math.abs(end.x-drag.x),h=Math.abs(end.y-drag.y);setDrag(null);setHover(null);if(w<.01||h<.01)return;if(calibrate){setReference({length:Math.hypot((end.x-drag.x)*dimensions[0],(end.y-drag.y)*dimensions[1]),drawing_id:drawing,page});setCalibrate(false);setNotice('Reference line selected. Enter its real length in metres and apply calibration.');return;}patch('highlights',[...estimate.highlights,{id:crypto.randomUUID(),drawing_id:drawing,page,x,y,w,h,name:markName,stage}]);setNotice('Highlighted region saved in draft. Enter verified dimensions to price its work.')}
 const calibration=(estimate.calibrations||{})[drawing+'#'+page];const metresPerPixel=calibration?.metresPerPixel||0;
 const regionMeasures=h=>({area:h.w*dimensions[0]*h.h*dimensions[1]*metresPerPixel**2,perimeter:2*(h.w*dimensions[0]+h.h*dimensions[1])*metresPerPixel});
 function addMeasured(h){if(!metresPerPixel)return alert('Calibrate the drawing against a known dimension first');const m=regionMeasures(h);setItem({...initialItem,description:h.name,trade:'Measured new work',drawing:(fileDocs.find(x=>x.id===drawing)?.document_no||'')+' p'+page,quantity:Number(m.area.toFixed(2)),unit:'m²',status:'Scaled drawing take-off — verify on site'});setNotice('Area '+m.area.toFixed(2)+' m² added to BOQ entry editor. Check before adding.')}
 const currentHighlights=(estimate.highlights||[]).filter(x=>x.drawing_id===drawing&&x.page===page);
 const sum=estimate.items.reduce((a,i)=>({materials:a.materials+num(i.quantity)*num(i.material_rate),plant:a.plant+num(i.quantity)*num(i.plant_rate),labour:a.labour+num(i.quantity)*num(i.labour_hours)*num(i.labour_rate)}),{materials:0,plant:0,labour:0});
 const direct=sum.materials+sum.plant+sum.labour,oh=direct*num(estimate.overheads)/100,profit=(direct+oh)*num(estimate.profit)/100,subtotal=direct+oh+profit,total=subtotal*(1+num(estimate.vat)/100);
 function addItem(){if(!item.description.trim())return alert('Please enter the BOQ description');patch('items',[...estimate.items,{...item,id:crypto.randomUUID()}]);setItem(initialItem)}
 async function readCSV(e,type){const f=e.target.files?.[0];if(!f)return;let rows;if(/\.xlsx?$/i.test(f.name)){const wb=XLSX.read(await f.arrayBuffer(),{type:'array'}),sheet=wb.Sheets[wb.SheetNames[0]];rows=XLSX.utils.sheet_to_json(sheet,{header:1,defval:''});const idx=rows.findIndex(r=>r.some(c=>String(c).toLowerCase()==='description'));rows=rows.slice(idx<0?0:idx);}else{const raw=await f.text();rows=raw.replace(/^\uFEFF/,'').trim().split(/\r?\n/).map(x=>x.split(',').map(y=>y.replace(/^"|"$/g,'').trim()));}const heads=(rows.shift()||[]).map(s=>String(s).toLowerCase().replace(/[\s_()£.-]/g,''));const at=(row,...keys)=>{const idx=heads.findIndex(h=>keys.includes(h));return idx<0?'':row[idx]};const additions=rows.map(r=>{const desc=at(r,'description','task','item','material');return desc?{...initialItem,id:crypto.randomUUID(),description:desc,trade:at(r,'tradespeople','trade','category')||'Imported',unit:at(r,'unit','uom')||'nr',material_rate:type==='materials'?num(at(r,'rate','price','unitprice','priceexclvat')):0,labour_hours:type==='labour'?num(at(r,'hours','time','hoursperunit')):0,labour_rate:type==='labour'?num(at(r,'hourlyrate','labourrate'))||(num(at(r,'priceexclvat'))&&num(at(r,'hours'))?num(at(r,'priceexclvat'))/num(at(r,'hours')):0):0,supplier:at(r,'supplier','merchant'),price_url:at(r,'url','link'),status:'Imported — check and match quantities'}:null}).filter(Boolean);patch('items',[...estimate.items,...additions]);setNotice('Imported '+additions.length+' items; check the rates and match them to measured work.');e.target.value=''}
 function makeRow(cells){return new TableRow({children:cells.map(v=>new TableCell({children:[new Paragraph(String(v??''))]}))})}
 async function makeWord(){if(!estimate.items.length)return alert('Add some BOQ items first');const cells=[makeRow(['Trade','Description','Qty','Unit','Materials','Plant','Labour','Total'])];estimate.items.forEach(i=>cells.push(makeRow([i.trade,i.description,i.quantity,i.unit,money(num(i.material_rate)*num(i.quantity)),money(num(i.plant_rate)*num(i.quantity)),money(num(i.labour_hours)*num(i.labour_rate)*num(i.quantity)),money(perLine(i))])));const para=t=>new Paragraph(String(t||''));const heading=t=>new Paragraph({text:t,heading:HeadingLevel.HEADING_2});let logoParagraph=[];if(builder?.logo_path){try{const {data:signed}=await db.storage.from('project-files').createSignedUrl(builder.logo_path,120);if(signed?.signedUrl){const bytes=new Uint8Array(await (await fetch(signed.signedUrl)).arrayBuffer());const ext=builder.logo_path.toLowerCase().split('.').pop();logoParagraph=[new Paragraph({children:[new ImageRun({data:bytes,type:ext==='jpg'||ext==='jpeg'?'jpg':'png',transformation:{width:180,height:80}})]})]}}catch(e){console.warn('Logo could not be embedded',e)}}const d=new Document({sections:[{children:[...logoParagraph,new Paragraph({children:[new TextRun({text:builder?.name||'Draft Builder Quotation',bold:true,size:34})]}),para([builder?.address,builder?.phone,builder?.email,builder?.vat_number&&'VAT: '+builder.vat_number].filter(Boolean).join(' | ')),heading('Bill of Quantities and Estimate'),para('Project: '+project.name+' | '+(project.project_no||'')),para('Site: '+(project.site_address||'')),para('Drawing highlights are scope indicators only. All quantities, specifications, labour times and current merchant prices require checking.'),new Table({rows:cells}),heading('Summary'),para('Materials: '+money(sum.materials)),para('Plant: '+money(sum.plant)),para('Labour: '+money(sum.labour)),para('Overheads / preliminaries ('+estimate.overheads+'%): '+money(oh)),para('Profit ('+estimate.profit+'%): '+money(profit)),para('Subtotal excluding VAT: '+money(subtotal)),para('VAT ('+estimate.vat+'%): '+money(total-subtotal)),para('Total including VAT: '+money(total)),heading('Qualifications'),para('Draft for review. No automatic scale measurement or live merchant-price confirmation is claimed.'),para(builder?.footer||'')] }]});const blob=await Packer.toBlob(d),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=(project.project_no||'project')+'-BOQ.docx';a.click();setTimeout(()=>URL.revokeObjectURL(url),2000)}
 return <section className="panel estimateMain"><h2>Estimates & Bill of Quantities</h2><p className="muted">Mark new work on proposed plans, compare against existing drawings, then build a quantity-checked materials, plant and labour estimate. Marked areas are not automatically measured: confirm dimensions and scale before pricing.</p>
 <div className="estimateToolbar"><label>Saved builder<select value={estimate.builder_id||''} onChange={e=>patch('builder_id',e.target.value)}><option value="">Select builder</option>{builders.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label><button onClick={()=>setBuilderForm({name:'',contact_name:'',address:'',phone:'',email:'',vat_number:'',company_number:'',footer:''})}>+ Save builder</button><button onClick={()=>save()} disabled={busy}>Save estimate</button><button onClick={makeWord}>Generate Word BOQ</button></div>
 {builderForm&&<div className="estimateForm"><h3>New builder / letterhead details</h3>{[['name','Company name'],['contact_name','Contact'],['address','Postal address'],['phone','Phone'],['email','Email'],['vat_number','VAT number'],['company_number','Company number'],['footer','Quotation footer']].map(([k,l])=><label key={k}>{l}<input value={builderForm[k]} onChange={e=>setBuilderForm(b=>({...b,[k]:e.target.value}))}/></label>)}<label>Company logo (PNG or JPEG)<input type="file" accept=".png,.jpg,.jpeg" onChange={e=>uploadBuilderLogo(e.target.files?.[0])}/></label><button onClick={createBuilder}>Save builder</button><button className="outline" onClick={()=>setBuilderForm(null)}>Cancel</button></div>}
 <h3>1. Highlight and measure new work</h3><p className="muted">Set an accurate scale using a dimension shown on the drawing. Click “Calibrate line”, drag along a known dimension, enter its real length in metres and save. Rectangle measurements are indicative take-off values and must be checked. Existing and proposed drawings are kept as separate layers; no automatic geometry subtraction is claimed.</p><div className="estimateToolbar"><button type="button" onClick={()=>setCalibrate(true)} disabled={!drawing}>Calibrate line</button><label>Known line length (m)<input type="number" min="0" step="any" value={calibrationMetres} onChange={e=>setCalibrationMetres(e.target.value)}/></label><button type="button" disabled={!reference||!num(calibrationMetres)} onClick={()=>{patch('calibrations',{...(estimate.calibrations||{}),[reference.drawing_id+'#'+reference.page]:{metresPerPixel:num(calibrationMetres)/reference.length,metres:num(calibrationMetres)}});setReference(null);setNotice('Drawing scale calibrated. You can now calculate area and perimeter of highlighted rectangles.')}}>Apply scale</button><span>{calibration?'Drag along a known drawing dimension':calibration?.metresPerPixel?'Calibrated':'Scale not set'}</span></div><div className="estimateToolbar"><label>Choose uploaded plan<select value={drawing} onChange={e=>{setDrawing(e.target.value);setPage(1)}}><option value="">Select existing or proposed PDF</option>{fileDocs.map(d=><option key={d.id} value={d.id}>{d.document_no||d.title}</option>)}</select></label><label>Area label<input value={markName} onChange={e=>setMarkName(e.target.value)}/></label><label>Drawing stage<select value={stage} onChange={e=>setStage(e.target.value)}><option>Proposed</option><option>Existing</option></select></label>{pageCount>1&&<label>Page<select value={page} onChange={e=>setPage(Number(e.target.value))}>{Array.from({length:pageCount},(_,i)=><option key={i} value={i+1}>{i+1}</option>)}</select></label>}</div>
 <div className="estimateDrawingScroll"><div className="estimateDrawing" style={image?{}:{width:dimensions[0]||800}}>{image?<img src={image} alt="Drawing to mark" onLoad={e=>setDimensions([e.currentTarget.naturalWidth,e.currentTarget.naturalHeight])}/>:<canvas ref={canvas}/>}<div ref={overlay} className="estimateOverlay" onPointerDown={start} onPointerMove={e=>drag&&setHover(point(e))} onPointerUp={finish}>{currentHighlights.map(h=><div key={h.id} className="estimateMark" style={{left:h.x*100+'%',top:h.y*100+'%',width:h.w*100+'%',height:h.h*100+'%'}} title={h.name+' — '+h.stage}/>) }{drag&&hover&&<div className="estimateMark drawingNew" style={{left:Math.min(drag.x,hover.x)*100+'%',top:Math.min(drag.y,hover.y)*100+'%',width:Math.abs(drag.x-hover.x)*100+'%',height:Math.abs(drag.y-hover.y)*100+'%'}}/>}</div></div></div><p className="muted">Click and drag a rectangle over a new-build or altered area. Save to the project using Save estimate. Highlights show scope only, not measured quantities.</p>
 {currentHighlights.map(h=><div key={h.id} className="estimateHighlightRow">{h.stage}: {h.name} (page {h.page}) {metresPerPixel?'— '+regionMeasures(h).area.toFixed(2)+' m², perimeter '+regionMeasures(h).perimeter.toFixed(2)+' m':''} <button type="button" onClick={()=>addMeasured(h)}>Add measured area to BOQ</button> <button className="outline" onClick={()=>patch('highlights',estimate.highlights.filter(x=>x.id!==h.id))}>Remove</button></div>)}
 <h3>2. Build measured BOQ items</h3><div className="estimateForm">{[['description','Work item / description'],['trade','Trade'],['drawing','Drawing reference'],['quantity','Verified quantity'],['material_rate','Material £/unit'],['plant_rate','Plant £/unit'],['labour_hours','Labour hours / unit'],['labour_rate','Labour £/hour'],['supplier','Supplier'],['price_url','Price source URL']].map(([k,l])=><label key={k}>{l}<input type={['quantity','material_rate','plant_rate','labour_hours','labour_rate'].includes(k)?'number':'text'} step="any" value={item[k]} onChange={e=>setItem(x=>({...x,[k]:e.target.value}))}/></label>)}<label>Unit<select value={item.unit} onChange={e=>setItem(x=>({...x,unit:e.target.value}))}>{['nr','m','m²','m³','kg','tonne','day','item'].map(x=><option key={x}>{x}</option>)}</select></label><button onClick={addItem}>Add BOQ item</button></div>
 <div className="estimateToolbar"><label>Import materials price CSV<input type="file" accept=".csv,.xlsx,.xls" onChange={e=>readCSV(e,'materials')}/></label><label>Import labour time CSV<input type="file" accept=".csv" onChange={e=>readCSV(e,'labour')}/></label></div><p className="muted">You can import your Construction_Rates_Master.xlsx directly. Its task descriptions, units, hours and prices need review against the intended cost basis. The importer does not merge duplicate lines or perform live scraping. Supplier links are recorded for checking.</p>
 <div className="estimateTableScroll"><table className="estimateTable"><thead><tr>{['Trade','Description','Qty','Unit','Materials','Plant','Labour','Total',''].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{estimate.items.map(x=><tr key={x.id}><td>{x.trade}</td><td>{x.description}<small>{x.drawing||''}</small></td><td>{x.quantity}</td><td>{x.unit}</td><td>{money(num(x.material_rate)*num(x.quantity))}</td><td>{money(num(x.plant_rate)*num(x.quantity))}</td><td>{money(num(x.labour_hours)*num(x.labour_rate)*num(x.quantity))}</td><td>{money(perLine(x))}</td><td><button className="outline" onClick={()=>patch('items',estimate.items.filter(y=>y.id!==x.id))}>Delete</button></td></tr>)}</tbody></table></div>
 <h3>3. Summary & pricing</h3><div className="estimateForm">{[['overheads','Preliminaries/overheads %'],['profit','Profit %'],['vat','VAT %']].map(([k,l])=><label key={k}>{l}<input type="number" min="0" step="any" value={estimate[k]} onChange={e=>patch(k,e.target.value)}/></label>)}</div><div className="estimateTotals"><span>Materials <b>{money(sum.materials)}</b></span><span>Plant <b>{money(sum.plant)}</b></span><span>Labour <b>{money(sum.labour)}</b></span><span>Overheads <b>{money(oh)}</b></span><span>Profit <b>{money(profit)}</b></span><span>Net <b>{money(subtotal)}</b></span><span>Inc VAT <b>{money(total)}</b></span></div>
 {notice&&<p role="status" className="notice">{notice}</p>}</section>
}
