import React,{useEffect,useState} from 'react';import{createRoot}from'react-dom/client';import{createClient}from'@supabase/supabase-js';import'./style.css';
const supabase=createClient(import.meta.env.VITE_SUPABASE_URL||'https://example.supabase.co',import.meta.env.VITE_SUPABASE_ANON_KEY||'missing');
const stages=['enquiry','information_required','scope_assessed','quoted','appointed','in_progress','awaiting_information','technical_review','issued','handover_complete'];
function App(){const[session,setSession]=useState(null),[projects,setProjects]=useState([]),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[msg,setMsg]=useState('');
useEffect(()=>{supabase.auth.getSession().then(x=>setSession(x.data.session));const{data:{subscription}}=supabase.auth.onAuthStateChange((_,s)=>setSession(s));return()=>subscription.unsubscribe()},[]);
useEffect(()=>{if(session)load()},[session]);async function load(){let{data,error}=await supabase.from('projects').select('*').order('created_at',{ascending:false});if(error)setMsg(error.message);else setProjects(data||[])}
async function login(e){e.preventDefault();let{error}=await supabase.auth.signInWithPassword({email,password});setMsg(error?.message||'')}
if(!session)return <main className="login"><section><Brand/><h2>Secure project management</h2><p>Principal Designer compliance, design review and controlled handover.</p><form onSubmit={login}><input placeholder="Email" value={email} onChange={e=>setEmail(e.target.value)}/><input type="password" placeholder="Password" value={password} onChange={e=>setPassword(e.target.value)}/><button>Sign in</button></form><small>{msg}</small></section></main>;
return <><header><Brand/><button className="outline" onClick={()=>supabase.auth.signOut()}>Sign out</button></header><div className="shell"><aside>{['Dashboard','Projects','Actions','Drawings','Changes','Documents','Payments','Handover','Admin'].map(x=><div>{x}</div>)}</aside><main><div className="top"><div><h1>Project Dashboard</h1><p>UK Principal Designers Ltd</p></div><button>+ New Project</button></div><div className="cards"><Card n={projects.length} t="Live projects"/><Card n={projects.filter(x=>x.risk==='red').length} t="Individual assessment"/><Card n={projects.filter(x=>x.status==='technical_review').length} t="Technical review"/><Card n={projects.filter(x=>x.scope_changed).length} t="Fee review"/></div><section className="panel"><h2>Projects</h2><table><thead><tr><th>Project</th><th>Offer</th><th>Status</th><th>Risk</th><th>Technical approval</th></tr></thead><tbody>{projects.map(p=><tr key={p.id}><td><b>{p.name}</b><br/><small>{p.project_no||''}</small></td><td>{p.offer_code||'—'}</td><td>{p.status.replaceAll('_',' ')}</td><td><span className={'risk '+p.risk}>{p.risk}</span></td><td>{p.competent_person_approved?'Approved':'Pending'}</td></tr>)}</tbody></table>{!projects.length&&<p className="empty">No projects yet. The database connection is ready for your first project.</p>}</section><section className="gate"><b>Technical declaration gate</b><p>A declaration cannot be released solely because a client has paid or uploaded photographs. Essential information, critical actions, technical review and competent-person approval must be complete.</p></section></main></div></>}
function Brand(){return <div className="brand"><strong><i>UK</i> PRINCIPAL<br/><span>DESIGNERS</span></strong><small>Expert Design Leadership for Safer Projects.</small></div>}function Card({n,t}){return <div className="card"><b>{n}</b><span>{t}</span></div>}createRoot(document.getElementById('root')).render(<App/>);